CFG_PATH = "../configuration.json"
ACTIVE_PATH = "../active.json"
ARTEMIS_PATH = "../artemis.json"
APPLY_PATH = "../apply.json"
TCACHE_PATH = "../territory_cache.json"
FORUMURL = "https://forums.wynncraft.com/threads/%E2%9C%AB%E2%8B%86-titans-valor-community-war-guild-%E2%99%94-recruiting-all-1.206094/page-"
